// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api/onebot.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OneBot_SendMsg_FullMethodName        = "/qqbot.api.OneBot/SendMsg"
	OneBot_SendPrivateMsg_FullMethodName = "/qqbot.api.OneBot/SendPrivateMsg"
	OneBot_SendGroupMsg_FullMethodName   = "/qqbot.api.OneBot/SendGroupMsg"
)

// OneBotClient is the client API for OneBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OneBotClient interface {
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error)
	SendPrivateMsg(ctx context.Context, in *SendPrivateMsgReq, opts ...grpc.CallOption) (*SendPrivateMsgResp, error)
	SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgResp, error)
}

type oneBotClient struct {
	cc grpc.ClientConnInterface
}

func NewOneBotClient(cc grpc.ClientConnInterface) OneBotClient {
	return &oneBotClient{cc}
}

func (c *oneBotClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error) {
	out := new(SendMsgResp)
	err := c.cc.Invoke(ctx, OneBot_SendMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oneBotClient) SendPrivateMsg(ctx context.Context, in *SendPrivateMsgReq, opts ...grpc.CallOption) (*SendPrivateMsgResp, error) {
	out := new(SendPrivateMsgResp)
	err := c.cc.Invoke(ctx, OneBot_SendPrivateMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oneBotClient) SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgResp, error) {
	out := new(SendGroupMsgResp)
	err := c.cc.Invoke(ctx, OneBot_SendGroupMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneBotServer is the server API for OneBot service.
// All implementations must embed UnimplementedOneBotServer
// for forward compatibility
type OneBotServer interface {
	SendMsg(context.Context, *SendMsgReq) (*SendMsgResp, error)
	SendPrivateMsg(context.Context, *SendPrivateMsgReq) (*SendPrivateMsgResp, error)
	SendGroupMsg(context.Context, *SendGroupMsgReq) (*SendGroupMsgResp, error)
	mustEmbedUnimplementedOneBotServer()
}

// UnimplementedOneBotServer must be embedded to have forward compatible implementations.
type UnimplementedOneBotServer struct {
}

func (UnimplementedOneBotServer) SendMsg(context.Context, *SendMsgReq) (*SendMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedOneBotServer) SendPrivateMsg(context.Context, *SendPrivateMsgReq) (*SendPrivateMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrivateMsg not implemented")
}
func (UnimplementedOneBotServer) SendGroupMsg(context.Context, *SendGroupMsgReq) (*SendGroupMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGroupMsg not implemented")
}
func (UnimplementedOneBotServer) mustEmbedUnimplementedOneBotServer() {}

// UnsafeOneBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OneBotServer will
// result in compilation errors.
type UnsafeOneBotServer interface {
	mustEmbedUnimplementedOneBotServer()
}

func RegisterOneBotServer(s grpc.ServiceRegistrar, srv OneBotServer) {
	s.RegisterService(&OneBot_ServiceDesc, srv)
}

func _OneBot_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneBotServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OneBot_SendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneBotServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OneBot_SendPrivateMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPrivateMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneBotServer).SendPrivateMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OneBot_SendPrivateMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneBotServer).SendPrivateMsg(ctx, req.(*SendPrivateMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OneBot_SendGroupMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneBotServer).SendGroupMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OneBot_SendGroupMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneBotServer).SendGroupMsg(ctx, req.(*SendGroupMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OneBot_ServiceDesc is the grpc.ServiceDesc for OneBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OneBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qqbot.api.OneBot",
	HandlerType: (*OneBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _OneBot_SendMsg_Handler,
		},
		{
			MethodName: "SendPrivateMsg",
			Handler:    _OneBot_SendPrivateMsg_Handler,
		},
		{
			MethodName: "SendGroupMsg",
			Handler:    _OneBot_SendGroupMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/onebot.proto",
}
