// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.3
// source: api/report.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReportReportEvent = "/qqbot.api.Report/ReportEvent"

type ReportHTTPServer interface {
	ReportEvent(context.Context, *ReportEventReq) (*ReportEventResp, error)
}

func RegisterReportHTTPServer(s *http.Server, srv ReportHTTPServer) {
	r := s.Route("/")
	r.POST("/report", _Report_ReportEvent0_HTTP_Handler(srv))
}

func _Report_ReportEvent0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportEventReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportReportEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportEvent(ctx, req.(*ReportEventReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReportEventResp)
		return ctx.Result(200, reply)
	}
}

type ReportHTTPClient interface {
	ReportEvent(ctx context.Context, req *ReportEventReq, opts ...http.CallOption) (rsp *ReportEventResp, err error)
}

type ReportHTTPClientImpl struct {
	cc *http.Client
}

func NewReportHTTPClient(client *http.Client) ReportHTTPClient {
	return &ReportHTTPClientImpl{client}
}

func (c *ReportHTTPClientImpl) ReportEvent(ctx context.Context, in *ReportEventReq, opts ...http.CallOption) (*ReportEventResp, error) {
	var out ReportEventResp
	pattern := "/report"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReportReportEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
